import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
const clip = Buffer.from(readFileSync(new URL('./clip.base64', import.meta.url), 'utf8'), 'base64');
const image = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64');
test('overview stays still; selected area plays four clips and releases them on close', async ({ page }) => {
  let downloads = 0;
  await page.route('**/jamcams.tfl.gov.uk/*.mp4*', route => { downloads++; return route.fulfill({ contentType: 'video/mp4', body: clip }); });
  await page.route('**/media/*.jpg', route => route.fulfill({ contentType: 'image/png', body: image }));
  await page.route('**/api/cctv/diagnostics?*', route => route.fulfill({ json: { checks: [{ state: 'HTTP_ERROR', httpStatus: 404, checkedAt: '2026-09-25T18:00:00Z' }] } }));
  await page.goto('/tools/camera-browser/');
  await expect(page.getByTestId('overview')).toContainText('SNAPSHOT · LOADED');
  expect(downloads).toBe(0);
  await page.getByRole('button', { name: 'Open camera', exact: true }).click();
  await expect(page.locator('video')).toHaveCount(4);
  await expect(page.getByText('CLIP · PLAYING', { exact: true })).toHaveCount(4);
  await expect(page.getByRole('region', { name: 'Camera viewing area' })).toContainText('SERVER HTTP 404');
  await page.screenshot({ path: 'test-results/camera-desktop.png' });
  await page.getByRole('button', { name: 'Switch camera', exact: true }).click();
  await expect(page.locator('h2')).toHaveText('Camera 5');
  await expect(page.locator('video')).toHaveCount(4);
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: true }); document.dispatchEvent(new Event('visibilitychange')); });
  await expect(page.locator('video')).toHaveCount(0);
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: false }); document.dispatchEvent(new Event('visibilitychange')); });
  await expect(page.locator('video')).toHaveCount(4);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/camera-mobile.png' });
  await page.getByRole('button', { name: 'Close cameras' }).click();
  await expect(page.locator('video')).toHaveCount(0);
});
test('clips refresh; media errors stay visible without inventing HTTP status', async ({ page }) => {
  let refreshed = false;
  await page.route('**/jamcams.tfl.gov.uk/*.mp4*', route => { refreshed ||= route.request().url().includes('_osiris='); return route.fulfill({ contentType: 'video/mp4', body: clip }); });
  await page.route('**/media/*.jpg', route => route.fulfill({ contentType: 'image/png', body: image }));
  await page.route('**/api/cctv/diagnostics?*', route => route.fulfill({ json: { checks: [{ state: 'UNKNOWN' }] } }));
  await page.clock.install();
  await page.goto('/tools/camera-browser/');
  await page.getByRole('button', { name: 'Open camera', exact: true }).click();
  await expect(page.getByText('CLIP · PLAYING', { exact: true })).toHaveCount(4);
  await page.clock.fastForward(300001);
  await expect.poll(() => refreshed).toBe(true);
  await page.locator('video').first().evaluate(el => { Object.defineProperty(el, 'error', { value: { code: 2 }, configurable: true }); el.dispatchEvent(new Event('error')); });
  await expect(page.getByText('CLIP · NETWORK', { exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Camera viewing area' })).not.toContainText('502');
  await expect(page.locator('video')).toHaveCount(4);
});
